### ISSUE TITLE
Copy Button Suggestion

### ISSUE THREAD

**Issue by belyazidi56** [MahmoudFettal/Password-Generator#1]
Hello @MahmoudFettal ,

I suggest to replace the copy button with an icon in the password Input

![image](https://user-images.githubusercontent.com/35711540/92671842-38218000-f30f-11ea-8893-780cceaf3c4a.png)

Thank you

**Comment by MahmoudFettal** [comment]
Hello

If your request is to put the icon inside the input, it is a good idea to be honest.

But me putting it that way isn't a bug it is a feature it was a UX idea of making that way so the copying of the code will be one click away. 

And thank you for your suggestion
